components/mapbox/Map.js, package-lock.json, yarn.lock
3 layers as base layers: OSM, ESRI Satellite and Mapbox. By default, ESRI Satellite.
=> Use BaseLayer in LayersControl

components/Navbar.js, components/Sidebar.js, components/Topbar.js, components/layout/Footer.js, components/layout/Header.js, pages/index.js
Updated design (Header/Sidebar/Footer)
=> Updated design (Header/Sidebar/Footer)

components/Sidebar.js, components/mapbox/Map.module.scss, pages/index.js
Hi Martin,
All done:
1. Sidebar width & height is fixed;
2. Updated design of Map (no gaps);
3. Added title "Menu" in Sidebar.
=> FixedHeightAndWidthOfSidebar+NewDesignOfMap

components/Sidebar.js, components/mapbox/Map.module.scss
=> ChangedSizeOfFooter

components/mapbox/Maplatest.js
Move the zoom buttons from the top-left to bottom-right of the map.
Also some linting and removal of extra new lines.
=> Move zoom buttons to bottom right

components/mapbox/Maplatest.js, context/FilterContext.js, context/LegendContext.js
Now 1st (health institutions) WMS link from GeoServer is working
=> WMS_links_works

components/mapbox/Maplatest.js
Added Vector Files;
Changed Layer Names in Geodatalayer menu
fixed depreacation warning
=> Prep_for_further_work

components/mapbox/Maplatest.js, reducer/reducer.js
Connected_WMS_to_Geodata_section
=> Connected_WMS_to_Geodata_section

components/leaflet/Map.js, config/MapConfiguration.js, public/static/mapbox_token.txt
Added Baselayers:
ESRI
STAMEN
-- Working on NASA nightlight layer
Extracted mapbox api access token and add to gitignore (next)
Changes to colors: Not done yet
=> New_baselayers_Color_fixes

components/controls/BetterWMSTileLayer.js, components/leaflet/Map.js, styles/globals.css
Added custom WMSTilelayer + FixedGetFeatureInfo.
At this stage applied only for Social Vulnerability > SV: XG Boost
=> AddedCustomWMSTilelayer+FixedGetFeatureInfo

components/leaflet/Map.js
Applied_newWMSTileLayer_to_AllGeoDataLayers
=> Applied_newWMSTileLayer_to_AllGeoDataLayers

components/controls/CustomPolygon.js, components/leaflet/Map.js
Area_Of_Interest_connected_to_GeoJeojson+Fixed_Hover_Of_Socioeconomic_Layers
=> Area_Of_Interest_connected_to_GeoJeojson+Fixed_Hover_Of_Socioeconomic_Layers

components/Sidebar.js, components/controls/CustomPopup.js, components/leaflet/Map.js, components/marker/CircleMarkersVulnerability.js, reducer/legendReducer.js, reducer/reducer.js
=> VulnerabilitySectionFixed

components/layout/Footer.js
The Twitter and Website links were swapped.
=> href links swapped in footer fixed

components/controls/BetterWMSTileLayer.js, components/leaflet/Map.js
=> Update occurrences of http to https

components/controls/NewLegend_2.js, components/leaflet/Map.js
=> newDragAndDropLegend

components/Sidebar.js, components/controls/NewLegend_2.js, components/leaflet/Map.js, reducer/reducer.js
=> V1_GeoServerLegendsAreWorking

components/Sidebar.js, components/controls/NewLegend_2.js, components/leaflet/Map.js, reducer/reducer.js
=> FixedLegends

components/leaflet/Map.js
=> New_V_0.1_LegendsForDHS

.gitignore, components/leaflet/Map.js, package-lock.json
=> WorkingVersion

components/Sidebar.js, components/controls/ControlMenu.js, package.json, styles/globals.css, yarn.lock
This is the same work as issue-info-box but no yarn install was done on this. So before pushing it was working perfectly fine. Also the package.json and yarn.lock files were committed.
=> Issue info box

components/controls/NewLegend_2.js
Fixed. Access legend using https and www.sdglab.ml
=> fixes #157. GetLegend using https

components/controls/InfoBox.js, components/controls/NewLegend_2.js, styles/globals.css
=> 196 small design change to legend

components/controls/InfoBox.js
changes in tab order and default tab
=> infoBox changes

components/Sidebar.js, reducer/reducer.js
=> high res layers follow desired order
